enum SubwayLine {
  One = "1",
  Two = "2",
  Three = "3",
  Four = "4",
  Five = "5",
  Six = "6",
  Seven = "7",
  A = "a",
  C = "c",
  E = "e",
  B = "b",
  D = "d",
  F = "f",
  M = "m",
  N = "n",
  Q = "q",
  R = "r",
  W = "w",
  J = "j",
  Z = "z",
  L = "l",
  G = "g",
  S = "s",
}

// same as SubwayLine, but sorted for the picker screen
const PICKER_LINES: SubwayLine[] = [
  SubwayLine.One,
  SubwayLine.Two,
  SubwayLine.Three,
  SubwayLine.Seven,
  SubwayLine.Four,
  SubwayLine.Five,
  SubwayLine.Six,
  SubwayLine.G,
  SubwayLine.A,
  SubwayLine.C,
  SubwayLine.E,
  SubwayLine.L,
  SubwayLine.B,
  SubwayLine.D,
  SubwayLine.F,
  SubwayLine.M,
  SubwayLine.N,
  SubwayLine.Q,
  SubwayLine.R,
  SubwayLine.W,
  SubwayLine.J,
  SubwayLine.Z,
  SubwayLine.S,
];

export { SubwayLine, PICKER_LINES };
